name: blinker
description: >
  A Flutter widget for blinking or fade-like color transitions on any widget.
  Supports fade effect between two colors or cycling through multiple colors.
  Works on all Flutter platforms: Android, iOS, Web, Windows, macOS, and Linux.
version: 1.0.0
homepage: https://github.com/AbdullahProjects/blinker
repository: https://github.com/AbdullahProjects/blinker
issue_tracker: https://github.com/AbdullahProjects/blinker/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
